dist: xenial
language: c
sudo: required
install: wget https://raw.githubusercontent.com/ocaml/ocaml-travisci-skeleton/master/.travis-opam.sh
script: bash -ex .travis-ci.sh
env:
  global:
  - PACKAGE=lmdb
  - secure: YWrGjdp0SFP1/MS6tB5MXy5QCuGbT+XQOG4eKHERegSiVdTVr/mBKRelmmMiSEpbRHwXpuNfNA4sYFfMsyV+2bf6W0cqQTXeITbm0CewuLxdxN0CZxyfIkcarhHLTq65xiKqWQpVPkjjP6gftmszWMKs2Xev/JwCWS4dbK/oihI=
matrix:
  include:
  - os: osx
    env: OCAML_VERSION=4.07
  - os: linux
    env: OCAML_VERSION=4.07 DOC=true
  - os: linux
    env: OCAML_VERSION=4.03
  - os: linux
    env: OCAML_VERSION=4.04
  - os: linux
    env: OCAML_VERSION=4.05
  - os: linux
    env: OCAML_VERSION=4.06
